constituent_list = {"MMM": "3M Co",
"ABT": "Abbott Laboratories",
"ABBV": "AbbVie Inc",
"ANF": "Abercrombie & Fitch CoA",
"ACN": "Accenture PlcA",
"ACE": "ACE Limited",
"ADBE": "Adobe Systems",
"ADT": "ADT Corp (The)",
"AES": "AES Corp",
"AET": "Aetna Inc",
"AFL": "AFLAC Inc",
"A": "Agilent Technologies",
"GAS": "AGL Resources",
"APD": "Air Products & Chem",
"ARG": "Airgas Inc",
"AKAM": "Akamai Technologies",
"AA": "Alcoa Inc",
"ALXN": "Alexion Pharmaceuticals",
"ATI": "Allegheny Technologies",
"AGN": "Allergan, Inc",
"ALL": "Allstate Corp",
"ALTR": "Altera Corp",
"MO": "Altria Group",
"AMZN": "Amazon.com Inc",
"AEP": "Amer Electric Pwr",
"AXP": "Amer Express",
"AIG": "Amer Intl Group",
"AMT": "Amer Tower",
"AEE": "Ameren Corp",
"AMP": "Ameriprise Financial",
"ABC": "AmerisourceBergen Corp",
"AME": "AMETEK, Inc",
"AMGN": "Amgen Inc",
"APH": "Amphenol CorpA",
"APC": "Anadarko Petroleum",
"ADI": "Analog Devices",
"AON": "Aon PLC",
"APA": "Apache Corp",
"AIV": "Apartment Investment & Mg",
"AAPL": "Apple Inc",
"AMAT": "Applied Materials",
"ADM": "Archer-Daniels-Midland",
"AIZ": "Assurant Inc",
"T": "AT&T Inc",
"ADSK": "Autodesk, Inc",
"ADP": "Automatic Data Proc",
"AN": "AutoNation Inc",
"AZO": "AutoZone Inc",
"AVB": "AvalonBay Communities",
"AVY": "Avery Dennison Corp",
"AVP": "Avon Products",
"BHI": "Baker Hughes Inc",
"BLL": "Ball Corp",
"BAC": "Bank of America",
"BK": "Bank of New York Mellon",
"BCR": "Bard (C.R.)",
"BAX": "Baxter Intl",
"BBT": "BB&T Corp",
"BEAM": "Beam Inc",
"BDX": "Becton, Dickinson",
"BBBY": "Bed Bath & Beyond",
"BMS": "Bemis Co",
"BRK.B": "Berkshire HathawayB",
"BBY": "Best Buy",
"BIIB": "Biogen Idec",
"BLK": "BlackRock Inc",
"BA": "Boeing Co",
"BWA": "Borg Warner",
"BXP": "Boston Properties",
"BSX": "Boston Scientific",
"BMY": "Bristol-Myers Squibb",
"BRCM": "Broadcom CorpA",
"BF.B": "Brown-FormanB",
"CHRW": "C.H. Robinson Worldwide",
"CA": "CA Inc",
"CVC": "Cablevision SysA",
"COG": "Cabot Oil & Gas",
"CAM": "Cameron Intl",
"CPB": "Campbell Soup",
"COF": "Capital One Financial",
"CAH": "Cardinal Health",
"CFN": "CareFusion Corp",
"KMX": "CarMax Inc",
"CCL": "Carnival Corp",
"CAT": "Caterpillar Inc",
"CBG": "CBRE GroupA",
"CBS": "CBS Corp B",
"CELG": "Celgene Corp",
"CNP": "CenterPoint Energy",
"CTL": "CenturyLink Inc",
"CERN": "Cerner Corp",
"CF": "CF Industries Hldgs",
"CHK": "Chesapeake Energy",
"CVX": "Chevron Corp",
"CMG": "Chipotle Mexican Grill",
"CB": "Chubb Corp",
"CI": "Cigna Corp",
"CINF": "Cincinnati Financial",
"CTAS": "Cintas Corp",
"CSCO": "Cisco Systems",
"C": "Citigroup Inc",
"CTXS": "Citrix Systems",
"CLF": "Cliffs Natural Resources",
"CLX": "Clorox Co",
"CME": "CME Group Inc",
"CMS": "CMS Energy",
"COH": "Coach Inc",
"KO": "Coca-Cola Co",
"CCE": "Coca-Cola Enterprises",
"CTSH": "Cognizant Tech Solutions",
"CL": "Colgate-Palmolive",
"CMCSA": "Comcast ClA",
"CMA": "Comerica Inc",
"CSC": "Computer Sciences",
"CAG": "ConAgra Foods",
"COP": "ConocoPhillips",
"CNX": "CONSOL Energy",
"ED": "Consolidated Edison",
"STZ": "Constellation BrandsA",
"GLW": "Corning Inc",
"COST": "Costco Wholesale",
"COV": "Covidien Plc",
"CCI": "Crown Castle Intl",
"CSX": "CSX Corp",
"CMI": "Cummins Inc",
"CVS": "CVS Caremark Corp",
"DHI": "D.R.Horton",
"DHR": "Danaher Corp",
"DRI": "Darden Restaurants",
"DVA": "DaVita HealthCare Partner",
"DE": "Deere & Co",
"DLPH": "Delphi Automotive PLC",
"DAL": "Delta Air Lines",
"DNR": "Denbury Resources",
"XRAY": "DENTSPLY Intl",
"DVN": "Devon Energy",
"DO": "Diamond Offshore Drilling",
"DTV": "DIRECTV",
"DFS": "Discover Financial Svcs",
"DISCA": "Discovery Communications",
"DIS": "Disney (Walt) Co",
"DG": "Dollar General",
"DLTR": "Dollar Tree",
"D": "Dominion Resources",
"DOV": "Dover Corp",
"DOW": "Dow Chemical",
"DPS": "Dr. Pepper Snapple Group",
"DTE": "DTE Energy",
"DUK": "Duke Energy",
"DNB": "Dun & Bradstreet",
"DD": "duPont(E.I.)deNemours",
"ETFC": "E Trade Financial",
"EMN": "Eastman Chemical",
"ETN": "Eaton Corp Plc",
"EBAY": "eBay Inc",
"ECL": "Ecolab Inc",
"EIX": "Edison Intl",
"EW": "Edwards Lifesciences",
"EA": "Electronic Arts",
"EMC": "EMC Corp",
"EMR": "Emerson Electric",
"ESV": "ENSCO Plc ClA",
"ETR": "Entergy Corp",
"EOG": "EOG Resources",
"EQT": "EQT Corp",
"EFX": "Equifax Inc",
"EQR": "Equity Residential",
"EXC": "Exelon Corp",
"EXPE": "Expedia Inc",
"EXPD": "Expeditors Intl,Wash",
"ESRX": "Express Scripts Holding",
"XOM": "Exxon Mobil",
"FFIV": "F5 Networks",
"FDO": "Family Dollar Stores",
"FAST": "Fastenal Co",
"FDX": "FedEx Corp",
"FIS": "Fidelity Natl Info Svcs",
"FITB": "Fifth Third Bancorp",
"FSLR": "First Solar",
"FE": "FirstEnergy Corp",
"FISV": "Fiserv Inc",
"FLIR": "FLIR Systems",
"FLS": "Flowserve Corp",
"FLR": "Fluor Corp",
"FMC": "FMC Corp",
"FTI": "FMC Technologies",
"F": "Ford Motor",
"FRX": "Forest Labs",
"FOSL": "Fossil Group",
"BEN": "Franklin Resources",
"FCX": "Freept McMoRan Copper&Go",
"FTR": "Frontier Communications",
"GME": "GameStop CorpA",
"GCI": "Gannett Co",
"GPS": "Gap Inc",
"GRMN": "Garmin Ltd",
"GM": "General Motors",
"GD": "Genl Dynamics",
"GE": "Genl Electric",
"GIS": "Genl Mills",
"GPC": "Genuine Parts",
"GNW": "Genworth FinancialA",
"GILD": "Gilead Sciences",
"GS": "Goldman Sachs Group",
"GT": "Goodyear Tire & Rub",
"GOOG": "Google IncA",
"GWW": "Grainger (W.W.)",
"HAL": "Halliburton Co",
"HOG": "Harley-Davidson",
"HAR": "Harman Intl",
"HRS": "Harris Corp",
"HIG": "Hartford Finl Svcs Gp",
"HAS": "Hasbro Inc",
"HCP": "HCP Inc",
"HCN": "Health Care REIT",
"HP": "Helmerich & Payne",
"HSY": "Hershey Co",
"HES": "Hess Corp",
"HPQ": "Hewlett-Packard",
"HD": "Home Depot",
"HON": "Honeywell Intl",
"HRL": "Hormel Foods",
"HSP": "Hospira Inc",
"HCBK": "Hudson City Bancorp",
"HUM": "Humana Inc",
"HBAN": "Huntington Bancshares",
"ITW": "Illinois Tool Works",
"IR": "Ingersoll-Rand Plc",
"TEG": "Integrys Energy Group",
"INTC": "Intel Corp",
"IPG": "Interpublic Grp Cos",
"IBM": "Intl Bus. Machines",
"IFF": "Intl Flavors/Fragr",
"IGT": "Intl Game Technology",
"IP": "Intl Paper",
"INTU": "Intuit Inc",
"ISRG": "Intuitive Surgical",
"IVZ": "INVESCO Ltd",
"IRM": "Iron Mountain",
"JBL": "Jabil Circuit",
"JEC": "Jacobs Engr Group",
"JNJ": "Johnson & Johnson",
"JCI": "Johnson Controls",
"JPM": "JPMorgan Chase & Co",
"JNPR": "Juniper Networks",
"KSU": "Kansas City Southern",
"K": "Kellogg Co",
"KEY": "KeyCorp",
"KMB": "Kimberly-Clark",
"KIM": "Kimco Realty",
"KMI": "Kinder Morgan",
"KLAC": "KLA-Tencor Corp",
"KSS": "Kohls Corp",
"KRFT": "Kraft Foods Group",
"KR": "Kroger Co",
"LTD": "L Brands",
"LLL": "L-3 Communications Hldgs",
"LH": "Laboratory Corp Amer Hldg",
"LRCX": "Lam Research",
"EL": "Lauder (Estee) Co",
"LM": "Legg Mason Inc",
"LEG": "Leggett & Platt",
"LEN": "Lennar CorpA",
"LUK": "Leucadia National",
"LIFE": "Life Technologies",
"LLY": "Lilly (Eli)",
"LNC": "Lincoln Natl Corp",
"LLTC": "Linear Technology Corp",
"LMT": "Lockheed Martin",
"L": "Loews Corp",
"LO": "Lorillard Inc",
"LOW": "Lowes Cos",
"LSI": "LSI Corp",
"LYB": "LyondellBasell Industries",
"MTB": "M&T Bank",
"MAC": "Macerich Co",
"M": "Macys Inc",
"MRO": "Marathon Oil",
"MPC": "Marathon Petroleum",
"MAR": "Marriott IntlA",
"MMC": "Marsh & McLennan",
"MAS": "Masco Corp",
"MA": "MasterCard IncA",
"MAT": "Mattel, Inc",
"MKC": "McCormick & Co",
"MCD": "McDonalds Corp",
"MHFI": "McGraw Hill Financial",
"MCK": "McKesson Corp",
"MJN": "Mead Johnson Nutrition",
"MWV": "MeadWestvaco Corp",
"MDT": "Medtronic, Inc",
"MRK": "Merck & Co",
"MET": "MetLife Inc",
"MCHP": "Microchip Technology",
"MU": "Micron Technology",
"MSFT": "Microsoft Corp",
"MOLX": "Molex Inc",
"TAP": "Molson Coors BrewingB",
"MDLZ": "Mondelez InternationalA",
"MON": "Monsanto Co",
"MNST": "Monster Beverage",
"MCO": "Moodys Corp",
"MS": "Morgan Stanley",
"MOS": "Mosaic Co",
"MSI": "Motorola Solutions",
"MUR": "Murphy Oil",
"MYL": "Mylan Inc",
"NBR": "Nabors Indus",
"NDAQ": "Nasdaq OMX Group",
"NOV": "Natl Oilwell Varco",
"NTAP": "NetApp Inc",
"NFLX": "NetFlix Inc",
"NWL": "Newell Rubbermaid",
"NFX": "Newfield Exploration",
"NEM": "Newmont Mining",
"NWSA": "News Corp Cl A",
"NEE": "NextEra Energy",
"NLSN": "Nielsen Holdings NV",
"NKE": "NIKE, IncB",
"NI": "NiSource Inc",
"NBL": "Noble Energy",
"JWN": "Nordstrom, Inc",
"NSC": "Norfolk Southern",
"NU": "Northeast Utilities",
"NTRS": "Northern Trust",
"NOC": "Northrop Grumman",
"NRG": "NRG Energy",
"NUE": "Nucor Corp",
"NVDA": "NVIDIA Corp",
"NYX": "NYSE Euronext",
"ORLY": "OReilly Automotive",
"OXY": "Occidental Petroleum",
"OMC": "Omnicom Group",
"OKE": "ONEOK Inc",
"ORCL": "Oracle Corp",
"OI": "Owens-Illinois",
"PCAR": "PACCAR Inc",
"PLL": "Pall Corp",
"PH": "Parker-Hannifin",
"PDCO": "Patterson Cos",
"PAYX": "Paychex Inc",
"BTU": "Peabody Energy",
"JCP": "Penney (J.C.)",
"PNR": "Pentair Ltd",
"PBCT": "Peoples United Financial",
"POM": "Pepco Holdings",
"PEP": "PepsiCo Inc",
"PKI": "PerkinElmer Inc",
"PRGO": "Perrigo Co",
"PETM": "PETsMART Inc",
"PFE": "Pfizer, Inc",
"PCG": "PG&E Corp",
"PM": "Philip Morris Intl",
"PSX": "Phillips 66",
"PNW": "Pinnacle West Capital",
"PXD": "Pioneer Natural Resources",
"PBI": "Pitney Bowes",
"PCL": "Plum Creek Timber",
"PNC": "PNC Financial Services Gr",
"PPG": "PPG Indus",
"PPL": "PPL Corp",
"PX": "Praxair Inc",
"PCP": "Precision Castparts",
"PCLN": "priceline.com Inc",
"PFG": "Principal Financial Grp",
"PG": "Procter & Gamble",
"PGR": "Progressive Corp,Ohio",
"PLD": "Prologis Inc",
"PRU": "Prudential Financial",
"PSA": "Public Storage",
"PEG": "Public Svc Enterprises",
"PHM": "PulteGroup Inc",
"QEP": "QEP Resources",
"QCOM": "QUALCOMM Inc",
"PWR": "Quanta Services",
"DGX": "Quest Diagnostics",
"RL": "Ralph Lauren CorpA",
"RRC": "Range Resources",
"RTN": "Raytheon Co",
"RHT": "Red Hat Inc",
"REGN": "Regeneron Pharmaceuticals",
"RF": "Regions Financial",
"RSG": "Republic Services",
"RAI": "Reynolds American",
"RHI": "Robert Half Intl",
"ROK": "Rockwell Automation",
"COL": "Rockwell Collins",
"ROP": "Roper Indus",
"ROST": "Ross Stores",
"RDC": "Rowan Cos Plc",
"R": "Ryder System",
"SWY": "Safeway Inc",
"CRM": "salesforce.com inc",
"SNDK": "SanDisk Corp",
"SCG": "SCANA Corp",
"SLB": "Schlumberger Ltd",
"SCHW": "Schwab(Charles)Corp",
"SNI": "Scripps Networks Interact",
"STX": "Seagate Technology Plc",
"SEE": "Sealed Air",
"SRE": "Sempra Energy",
"SHW": "Sherwin-Williams",
"SIAL": "Sigma-Aldrich",
"SPG": "Simon Property Group",
"SLM": "SLM Corp",
"SJM": "Smucker (J.M.)",
"SNA": "Snap-On Inc",
"SO": "Southern Co",
"LUV": "Southwest Airlines",
"SWN": "Southwestern Energy",
"SE": "Spectra Energy",
"STJ": "St. Jude Medical",
"SWK": "Stanley Black & Decker",
"SPLS": "Staples Inc",
"SBUX": "Starbucks Corp",
"HOT": "Starwood Hotels&Res World",
"STT": "State Street Corp",
"SRCL": "Stericycle Inc",
"SYK": "Stryker Corp",
"STI": "SunTrust Banks",
"SYMC": "Symantec Corp",
"SYY": "Sysco Corp",
"TROW": "T.Rowe Price Group",
"TGT": "Target Corp",
"TEL": "TE Connectivity",
"TE": "TECO Energy",
"THC": "Tenet Healthcare",
"TDC": "Teradata Corp",
"TER": "Teradyne Inc",
"TSO": "Tesoro Corp",
"TXN": "Texas Instruments",
"TXT": "Textron, Inc",
"TMO": "Thermo Fisher Scientific",
"TIF": "Tiffany & Co",
"TWX": "Time Warner",
"TWC": "Time Warner Cable",
"TJX": "TJX Companies",
"TMK": "Torchmark Corp",
"TSS": "Total System Svcs",
"TRV": "Travelers Cos",
"TRIP": "TripAdvisor Inc",
"FOXA": "Twenty-First Century Fox",
"TYC": "Tyco Intl",
"TSN": "Tyson FoodsA",
"USB": "U.S. Bancorp",
"X": "U.S. Steel",
"UNP": "Union Pacific",
"UPS": "United ParcelB",
"UTX": "United Technologies",
"UNH": "UnitedHealth Group",
"UNM": "Unum Group",
"URBN": "Urban Outfitters",
"VLO": "Valero Energy",
"VAR": "Varian Medical Systems",
"VTR": "Ventas Inc",
"VRSN": "VeriSign Inc",
"VZ": "Verizon Communications",
"VRTX": "Vertex Pharmaceuticals",
"VFC": "VF Corp",
"VIAB": "Viacom IncB",
"V": "Visa IncA",
"VNO": "Vornado Realty Trust",
"VMC": "Vulcan Materials",
"WMT": "Wal-Mart Stores",
"WAG": "Walgreen Co",
"WPO": "Washington PostB",
"WM": "Waste Management",
"WAT": "Waters Corp",
"WLP": "WellPoint Inc",
"WFC": "Wells Fargo",
"WDC": "Western Digital",
"WU": "Western Union",
"WY": "Weyerhaeuser Co",
"WHR": "Whirlpool Corp",
"WFM": "Whole Foods Market",
"WMB": "Williams Cos",
"WIN": "Windstream Holdings",
"WEC": "Wisconsin Energy Corp",
"WPX": "WPX Energy",
"WYN": "Wyndham Worldwide",
"WYNN": "Wynn Resorts",
"XEL": "Xcel Energy",
"XRX": "Xerox Corp",
"XLNX": "Xilinx Inc",
"XL": "XL Group PlcA",
"XYL": "Xylem Inc",
"YHOO": "Yahoo Inc",
"YUM": "Yum Brands",
"ZMH": "Zimmer Holdings",
"ZION": "Zions Bancorp",
"ZTS": "Zoetis IncA"}
